//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project_Job_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication_Tab
    {
        public int ApplicationId { get; set; }
        public int JobId { get; set; }
        public int EmployeeId { get; set; }
        public string ResumePath { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string ApplicationStatus { get; set; }
    
        public virtual Employee_Tab Employee_Tab { get; set; }
        public virtual JobDetails_Tab JobDetails_Tab { get; set; }
    }
}
