//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project_Job_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetails_Tab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobDetails_Tab()
        {
            this.JobApplication_Tab = new HashSet<JobApplication_Tab>();
        }
    
        public int JobId { get; set; }
        public int CompanyId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string SkillsRequired { get; set; }
        public int ExperienceRequired { get; set; }
        public string Qualification { get; set; }
        public decimal Salary { get; set; }
        public string JobType { get; set; }
        public string Location { get; set; }
        public System.DateTime LastDate { get; set; }
        public System.DateTime PostedDate { get; set; }
        public bool Status { get; set; }
    
        public virtual Company_Tab Company_Tab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplication_Tab> JobApplication_Tab { get; set; }
    }
}
