//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project_Job_Portal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MVC_Project_Job_PortalEntities : DbContext
    {
        public MVC_Project_Job_PortalEntities()
            : base("name=MVC_Project_Job_PortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company_Tab> Company_Tab { get; set; }
        public virtual DbSet<Employee_Tab> Employee_Tab { get; set; }
        public virtual DbSet<JobApplication_Tab> JobApplication_Tab { get; set; }
        public virtual DbSet<JobDetails_Tab> JobDetails_Tab { get; set; }
        public virtual DbSet<Login_Tab> Login_Tab { get; set; }
    
        public virtual int sp_DeleteJob(Nullable<int> jid)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteJob", jidParameter);
        }
    
        public virtual ObjectResult<sp_GetAllJobs_Result> sp_GetAllJobs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllJobs_Result>("sp_GetAllJobs");
        }
    
        public virtual ObjectResult<sp_GetCompanyById_Result> sp_GetCompanyById(Nullable<int> cid)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCompanyById_Result>("sp_GetCompanyById", cidParameter);
        }
    
        public virtual ObjectResult<sp_GetEmployeeById_Result> sp_GetEmployeeById(Nullable<int> eid)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetEmployeeById_Result>("sp_GetEmployeeById", eidParameter);
        }
    
        public virtual ObjectResult<sp_GetJobById_Result> sp_GetJobById(Nullable<int> jid)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetJobById_Result>("sp_GetJobById", jidParameter);
        }
    
        public virtual int sp_InsertCompany(Nullable<int> cid, string cname, string email, string ph, string ws, string desc, string loc)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("cname", cname) :
                new ObjectParameter("cname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var wsParameter = ws != null ?
                new ObjectParameter("ws", ws) :
                new ObjectParameter("ws", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertCompany", cidParameter, cnameParameter, emailParameter, phParameter, wsParameter, descParameter, locParameter);
        }
    
        public virtual int sp_InsertEmployee(Nullable<int> eid, string fname, string lname, Nullable<int> age, string addr, string em, string ph, string gen, Nullable<System.DateTime> dob, string qual, string skl, string res, string profimg)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var genParameter = gen != null ?
                new ObjectParameter("gen", gen) :
                new ObjectParameter("gen", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var qualParameter = qual != null ?
                new ObjectParameter("qual", qual) :
                new ObjectParameter("qual", typeof(string));
    
            var sklParameter = skl != null ?
                new ObjectParameter("skl", skl) :
                new ObjectParameter("skl", typeof(string));
    
            var resParameter = res != null ?
                new ObjectParameter("res", res) :
                new ObjectParameter("res", typeof(string));
    
            var profimgParameter = profimg != null ?
                new ObjectParameter("profimg", profimg) :
                new ObjectParameter("profimg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertEmployee", eidParameter, fnameParameter, lnameParameter, ageParameter, addrParameter, emParameter, phParameter, genParameter, dobParameter, qualParameter, sklParameter, resParameter, profimgParameter);
        }
    
        public virtual int sp_InsertJob(Nullable<int> cid, string jobtitle, string jobdesc, string skreq, Nullable<int> expreq, string qualreq, Nullable<decimal> sal, string jobtype, string loc, Nullable<System.DateTime> lastdate)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jobtitleParameter = jobtitle != null ?
                new ObjectParameter("jobtitle", jobtitle) :
                new ObjectParameter("jobtitle", typeof(string));
    
            var jobdescParameter = jobdesc != null ?
                new ObjectParameter("jobdesc", jobdesc) :
                new ObjectParameter("jobdesc", typeof(string));
    
            var skreqParameter = skreq != null ?
                new ObjectParameter("skreq", skreq) :
                new ObjectParameter("skreq", typeof(string));
    
            var expreqParameter = expreq.HasValue ?
                new ObjectParameter("expreq", expreq) :
                new ObjectParameter("expreq", typeof(int));
    
            var qualreqParameter = qualreq != null ?
                new ObjectParameter("qualreq", qualreq) :
                new ObjectParameter("qualreq", typeof(string));
    
            var salParameter = sal.HasValue ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(decimal));
    
            var jobtypeParameter = jobtype != null ?
                new ObjectParameter("jobtype", jobtype) :
                new ObjectParameter("jobtype", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var lastdateParameter = lastdate.HasValue ?
                new ObjectParameter("lastdate", lastdate) :
                new ObjectParameter("lastdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertJob", cidParameter, jobtitleParameter, jobdescParameter, skreqParameter, expreqParameter, qualreqParameter, salParameter, jobtypeParameter, locParameter, lastdateParameter);
        }
    
        public virtual int sp_UpdateJob(string jobdesc, string sklreq, Nullable<int> expreq, string qual, Nullable<decimal> sal, string jobtype, string loc, Nullable<System.DateTime> lastdate)
        {
            var jobdescParameter = jobdesc != null ?
                new ObjectParameter("jobdesc", jobdesc) :
                new ObjectParameter("jobdesc", typeof(string));
    
            var sklreqParameter = sklreq != null ?
                new ObjectParameter("sklreq", sklreq) :
                new ObjectParameter("sklreq", typeof(string));
    
            var expreqParameter = expreq.HasValue ?
                new ObjectParameter("expreq", expreq) :
                new ObjectParameter("expreq", typeof(int));
    
            var qualParameter = qual != null ?
                new ObjectParameter("qual", qual) :
                new ObjectParameter("qual", typeof(string));
    
            var salParameter = sal.HasValue ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(decimal));
    
            var jobtypeParameter = jobtype != null ?
                new ObjectParameter("jobtype", jobtype) :
                new ObjectParameter("jobtype", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var lastdateParameter = lastdate.HasValue ?
                new ObjectParameter("lastdate", lastdate) :
                new ObjectParameter("lastdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateJob", jobdescParameter, sklreqParameter, expreqParameter, qualParameter, salParameter, jobtypeParameter, locParameter, lastdateParameter);
        }
    
        public virtual int sp_UpdateJobStatus(Nullable<bool> status)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateJobStatus", statusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MaxIdLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MaxIdLogin");
        }
    
        public virtual int sp_Login(Nullable<int> regid, string uname, string pw, string utype)
        {
            var regidParameter = regid.HasValue ?
                new ObjectParameter("regid", regid) :
                new ObjectParameter("regid", typeof(int));
    
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var utypeParameter = utype != null ?
                new ObjectParameter("utype", utype) :
                new ObjectParameter("utype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Login", regidParameter, unameParameter, pwParameter, utypeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GetRegId(string uname, string pw)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GetRegId", unameParameter, pwParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LoginCountId(string uname, string pw)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LoginCountId", unameParameter, pwParameter);
        }
    
        public virtual ObjectResult<string> sp_LoginType(string uname, string pw)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_LoginType", unameParameter, pwParameter);
        }
    
        public virtual ObjectResult<string> sp_GetCompanyName(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetCompanyName", companyIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GetJobsCountByCompany(Nullable<int> cid)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GetJobsCountByCompany", cidParameter);
        }
    
        public virtual ObjectResult<sp_ViewPostedJobs_Result> sp_ViewPostedJobs(Nullable<int> cid)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ViewPostedJobs_Result>("sp_ViewPostedJobs", cidParameter);
        }
    
        public virtual ObjectResult<sp_GetApplicationsByEmployee_Result> sp_GetApplicationsByEmployee(Nullable<int> eid)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetApplicationsByEmployee_Result>("sp_GetApplicationsByEmployee", eidParameter);
        }
    
        public virtual ObjectResult<string> sp_GetResumeByEmployeeId(Nullable<int> eid)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetResumeByEmployeeId", eidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CheckApplicationExists(Nullable<int> jid, Nullable<int> eid)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CheckApplicationExists", jidParameter, eidParameter);
        }
    
        public virtual int sp_ApplyJob(Nullable<int> jid, Nullable<int> eid)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ApplyJob", jidParameter, eidParameter);
        }
    
        public virtual ObjectResult<sp_GetApplicantsByJob_Result> sp_GetApplicantsByJob(Nullable<int> jid)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetApplicantsByJob_Result>("sp_GetApplicantsByJob", jidParameter);
        }
    }
}
